services:
  - type: web
    name: baber-client-site3
    env: docker
    plan: free
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      # On Render free tier, persistent disks are not supported.
      # If later upgrading to a paid plan with disk, you can re-add DATA_DIR=/data
      # and a disk section. For free plan, omit disk and use ephemeral storage
      # or switch to an external DB.
